#!/bin/bash

led="$1"; shift
case "$1" in
  off)
    echo none > /sys/class/leds/$led/trigger
    ;;
  blink)
    echo timer > /sys/class/leds/$led/trigger
    sleep 0.5
    echo ${2:-100} > /sys/class/leds/$led/delay_on
    echo ${3:-100} > /sys/class/leds/$led/delay_off
    ;;
  trigger)
    echo $2 > /sys/class/leds/$led/trigger
    ;;
  triggers)
    cat /sys/class/leds/$led/trigger
    ;;
esac
